image: node:14-slim
clone:
  depth: full
options:
  max-time: 30 # maximum amount of minutes a step can execute
definitions:
  caches:
    sonar: /root/.sonar/cache

stepdefinitions:
  - lint: &lint
      name: Lint
      caches:
        - node
      script:
        - yarn install
        - yarn lint
        #- yarn lint-md
  - test: &test
      name: Test and Analyze
      caches:
        - node
      script:
        - yarn install
        - yarn test
      artifacts: # defining the artifacts to be passed to each future step.
        - packages/components/coverage/**
  - sonar: &sonar
      name: Sonar Analysis
      caches:
        - node
      script:
        - npm install -g sonarqube-scanner
        - sonar-scanner -Dsonar.login=$SONAR_TOKEN
          -Dsonar.organization=$SONAR_ORGANIZATION
          -Dsonar.projectKey=$SONAR_PROJECT_KEY
          -Dsonar.branch.name=$BITBUCKET_BRANCH
  - audit: &audit
      name: Audit (yarn)
      caches:
        - node
      script:
        - yarn audit || true #Temp disabled
  - build: &build
      name: Build
      caches:
        - node
      script:
        - apt update && apt install -y zip
        - yarn install
        - yarn build
        - cd packages/components/
        - yarn build-storybook
        - cd storybook-static
        - zip -r storybook-$BITBUCKET_BUILD_NUMBER.zip .
      artifacts:
        - "packages/components/storybook-static/storybook-*.zip"

pipelines:
  pull-requests:
    '**':
      - parallel:
        - step: *lint
        - step: *test
        - step: *audit
      - step: *sonar
      - step: *build
      - step:
          name: "Create Preview"
          script:
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID_DEV
                AZURE_PASSWORD: $AZURE_PASSWORD_DEV
                AZURE_TENANT_ID: $AZURE_TENANT_ID_DEV
                CLI_COMMAND: 'az webapp create --name ase-storybook-marketplace-pr-$BITBUCKET_PR_ID --resource-group $AZURE_RESOURCE_GROUP_DEV --plan plan-shared-marketplace-dev-switzerlandnorth-001'
      - step:
          name: "Deploy Preview"
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.4
              variables:
                AZURE_APP_ID: $AZURE_APP_ID_DEV
                AZURE_PASSWORD: $AZURE_PASSWORD_DEV
                AZURE_TENANT_ID: $AZURE_TENANT_ID_DEV
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP_DEV
                AZURE_APP_NAME: ase-storybook-marketplace-pr-$BITBUCKET_PR_ID
                ZIP_FILE: 'packages/components/storybook-static/storybook-$BITBUCKET_BUILD_NUMBER.zip'
  branches:
    main:
      - parallel:
          - step: *lint
          - step: *test
          - step: *audit
      - step: *sonar
      - step: *build
      - step:
          name: "Publish packages"
          script:
            - apt update && apt install -y git cl-base64
            - yarn install
            - npm install --global lerna
            - npm config set @mch-group:registry https://registry.npmjs.org && npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
            - git config --unset core.hooksPath
            - lerna init
            - lerna version --conventional-commits --yes --no-git-tag-version --no-push
            # Configure git to use ssh.
            - git remote set-url origin ${BITBUCKET_GIT_SSH_ORIGIN}
            - echo $PRIVATE_KEY > ~/.ssh/id_rsa.tmp
            - base64 -d ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            # Publish packages.
            - git commit -am "[ci skip] Publish Chore (release)" --no-verify
            - git push
            - lerna publish from-package --yes
      - step:
          name: "Delete Preview"
          image: mcr.microsoft.com/azure-cli
          script:
            - az login --service-principal -u $AZURE_APP_ID_DEV -p $AZURE_PASSWORD_DEV --tenant $AZURE_TENANT_ID_DEV
            - PR=$(curl -s -u $BITBUCKET_ADMIN_USER:$BITBUCKET_ADMIN_PASSWORD https://api.bitbucket.org/2.0/repositories/mchappsrvcs/artbasel-ui-kit/pullrequests?state=MERGED | jq -s '.[].values[].id' | sort > pullRequestList.txt)
            - WEB_APP=$(az webapp list --query "[?state=='Running']" | jq '.[].name'| grep 'pr' | cut -c 31-33 | tr -d '"' | sort > webappList.txt)
            - COMPARE=$(comm -12 pullRequestList.txt webappList.txt)
            - echo "List of Web App services to delete"
            - for x in $COMPARE; do echo "ase-storybook-marketplace-pr-$x"; done
            - for p in $COMPARE; do az webapp delete --name ase-storybook-marketplace-pr-$p --resource-group $AZURE_RESOURCE_GROUP_DEV; done
      - step:
          name: "Deploy"
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.4
              variables:
                AZURE_APP_ID: $AZURE_APP_ID_DEV
                AZURE_PASSWORD: $AZURE_PASSWORD_DEV
                AZURE_TENANT_ID: $AZURE_TENANT_ID_DEV
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP_DEV
                AZURE_APP_NAME: $AZURE_APP_NAME_DEV
                ZIP_FILE: 'packages/components/storybook-static/storybook-$BITBUCKET_BUILD_NUMBER.zip'
