/* eslint-disable */
// Generated by gulp svg-icon - do not modify manually

import React from 'react';
import PropTypes from 'prop-types';

export const IconList = [
  'add',
  'add-info',
  'archive',
  'attach',
  'backarrow',
  'backtotoparrow',
  'backarrow-button',
  'calendar',
  'camera',
  'catalog',
  'certificate',
  'chat',
  'check',
  'close',
  'collections-add',
  'colour',
  'condition-report',
  'copy',
  'dashboard',
  'delete',
  'download',
  'drag',
  'dropdown',
  'edit',
  'enter',
  'event',
  'event-attending',
  'exit',
  'eye-hide',
  'eye-view',
  'facebook',
  'favourite',
  'favourite-filled',
  'filter',
  'floorplan',
  'follow',
  'fullscreen',
  'fullscreen-exit',
  'gallery',
  'grid',
  'grid-alternative',
  'guest',
  'guest-add',
  'guest-added',
  'guest-added-alternative',
  'headphones',
  'help',
  'home',
  'hotel',
  'hotel-alternative',
  'info',
  'instagram',
  'institution',
  'key',
  'link',
  'linkarrow',
  'linkbroken',
  'linkedIn',
  'list',
  'list-alternative',
  'live-chat',
  'locate',
  'lock',
  'mail',
  'map',
  'menu',
  'move',
  'note',
  'organise',
  'ovr-list',
  'pause',
  'pause-alternative',
  'pin',
  'play',
  'playback',
  'playlist',
  'recommendation',
  'redirect',
  'refresh',
  'reply',
  'report',
  'report-alternative',
  'restaurant',
  'room-view',
  'search',
  'settings',
  'share',
  'sorting',
  'subtitle',
  'telephone',
  'ticket',
  'time',
  'twitter',
  'unlock',
  'vip',
  'vip-card',
  'volume',
  'warning',
  'web',
  'weebo',
  'whatsapp',
  'world',
  'youtube',
  'zoomin',
  'zoomout',
];

const Icon = ({
  className,
  color,
  height,
  width,
  name,
  onClick,
  size,
  style,
  ...rest
}) => {
  const getIcon = (name) => {
    switch (name) {
      default:
        return null;
      case 'add':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M11.25 12.75V20h1.5v-7.25H20v-1.5h-7.25V4h-1.5v7.25H4v1.5h7.25z" />
          </svg>
        );
      case 'add-info':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M8 7l5 5-5 5v-4H2v-2h6V7zM13 7h9v2h-9V7zM13 15h9v2h-9v-2zM22 11h-6v2h6v-2z" />
          </svg>
        );
      case 'archive':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M20 4l-3 .02L16 3H8L7 4H4v1.484L20 5.5V4zM7.154 20.5a.655.655 0 0 1-.654-.643V8.5h11v11.357c0 .343-.29.643-.654.643H7.154zM19 7H5v12.857C5 21.036 5.97 22 7.154 22h9.692A2.155 2.155 0 0 0 19 19.857V7zm-9.453 6.487l-1.094 1.026 3.543 3.775 3.55-3.774-1.092-1.028-1.708 1.815V11h-1.5v4.297l-1.7-1.81z"
            />
          </svg>
        );
      case 'attach':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M16.5 6v11.5c0 2.21-1.79 4-4 4s-4-1.79-4-4V5a2.5 2.5 0 0 1 5 0v10.5c0 .55-.45 1-1 1s-1-.45-1-1V6H10v9.5a2.5 2.5 0 0 0 5 0V5c0-2.21-1.79-4-4-4S7 2.79 7 5v12.5c0 3.04 2.46 5.5 5.5 5.5s5.5-2.46 5.5-5.5V6h-1.5z" />
          </svg>
        );
      case 'backarrow':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M10.75 17.847l-5.24-5.141L21 12.607l-.033-1.516-15.522-.033 5.273-5.207-1.12-1.12-7.218 7.118L9.63 19l1.12-1.153z"
            />
          </svg>
        );
      case 'backtotoparrow':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M6.153 10.7526L11.2942 5.5126L11.393 21.002L12.909 20.969L12.942 5.44669L18.149 10.7197L19.2695 9.59916L12.151 2.38177L4.99953 9.63212L6.153 10.7526Z"
            />
          </svg>
        );
      case 'backarrow-button':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 9 14"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M2.71 6.776l5.422 5.422-1.355 1.355-5.422-5.421L0 6.776 6.777 0l1.355 1.355L2.71 6.776z"
            />
          </svg>
        );
      case 'calendar':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M8.5 2H7v1.5H3v18h18v-18h-4V2h-1.5v1.5h-7V2zm7 4V5h-7v1H7V5H4.5v3.25h15V5H17v1h-1.5zm4 3.75h-15V20h15V9.75z"
            />
          </svg>
        );
      case 'camera':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M15.2 13a3.2 3.2 0 1 1-6.4 0 3.2 3.2 0 0 1 6.4 0z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M7.17 5L9 3h6l1.83 2H20c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V7c0-1.1.9-2 2-2h3.17zM7 13c0 2.76 2.24 5 5 5s5-2.24 5-5-2.24-5-5-5-5 2.24-5 5z"
            />
          </svg>
        );
      case 'catalog':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M21 5H3v14h8l1 1 1-1h8V5zM4.5 6.5h6.75v11H4.5v-11zm8.25 0v11h6.75v-11h-6.75z"
            />
          </svg>
        );
      case 'certificate':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M23 12l-2.44-2.79.34-3.69-3.61-.82-1.89-3.2L12 2.96 8.6 1.5 6.71 4.69 3.1 5.5l.34 3.7L1 12l2.44 2.79-.34 3.7 3.61.82L8.6 22.5l3.4-1.47 3.4 1.46 1.89-3.19 3.61-.82-.34-3.69L23 12zm-12.91 4.72l-3.8-3.81 1.48-1.48 2.32 2.33 5.85-5.87 1.48 1.48-7.33 7.35z" />
          </svg>
        );
      case 'chat':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M20 3H4c-1.1 0-1.99.9-1.99 2L2 23l4-4h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM6 10h12v2H6v-2zm8 5H6v-2h8v2zm4-6H6V7h12v2z" />
          </svg>
        );
      case 'check':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M18.455 6.484l1.09 1.032-9.504 10.03-5.543-4.988 1.003-1.115 4.457 4.01 8.497-8.969z" />
          </svg>
        );
      case 'close':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M6.515 4.758l-1.41 1.409 5.567 5.566-5.834 5.834 1.329 1.328L12 13.061l5.834 5.834 1.409-1.41-5.834-5.833 5.486-5.485-1.329-1.328-5.485 5.485-5.566-5.566z"
            />
          </svg>
        );
      case 'collections-add':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10zm.969-15.5H11.03v4.531H6.5v1.938h4.531V17.5h1.938v-4.531H17.5V11.03h-4.531V6.5z"
            />
          </svg>
        );
      case 'colour':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M12 3a9 9 0 0 0 0 18c.83 0 1.5-.67 1.5-1.5 0-.39-.15-.74-.39-1.01-.23-.26-.38-.61-.38-.99 0-.83.67-1.5 1.5-1.5H16c2.76 0 5-2.24 5-5 0-4.42-4.03-8-9-8zm-5.5 9c-.83 0-1.5-.67-1.5-1.5S5.67 9 6.5 9 8 9.67 8 10.5 7.33 12 6.5 12zm3-4C8.67 8 8 7.33 8 6.5S8.67 5 9.5 5s1.5.67 1.5 1.5S10.33 8 9.5 8zm5 0c-.83 0-1.5-.67-1.5-1.5S13.67 5 14.5 5s1.5.67 1.5 1.5S15.33 8 14.5 8zm3 4c-.83 0-1.5-.67-1.5-1.5S16.67 9 17.5 9s1.5.67 1.5 1.5-.67 1.5-1.5 1.5z" />
          </svg>
        );
      case 'condition-report':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M19 3h-4.18C14.4 1.84 13.3 1 12 1c-1.3 0-2.4.84-2.82 2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 0c.55 0 1 .45 1 1s-.45 1-1 1-1-.45-1-1 .45-1 1-1zm2 14H7v-2h7v2zm3-4H7v-2h10v2zm0-4H7V7h10v2z" />
          </svg>
        );
      case 'copy':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M6 5.889C6 5.398 6.398 5 6.889 5H20.11c.491 0 .889.398.889.889V21.11c0 .491-.398.889-.889.889H6.89A.889.889 0 0 1 6 21.111V5.89zm1.333 14.778V6.333h12.334v14.334H7.333z"
            />
            <path d="M4.333 17.667V3.333h12.334V4H18V2.889A.889.889 0 0 0 17.111 2H3.89A.889.889 0 0 0 3 2.889V18.11c0 .491.398.889.889.889H5v-1.333h-.667z" />
            <path d="M10 13h7v1h-7z" />
            <path d="M14 10v7h-1v-7z" />
          </svg>
        );
      case 'dashboard':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M3 13h8V3H3v10zm0 8h8v-6H3v6zm10 0h8V11h-8v10zm0-18v6h8V3h-8z" />
          </svg>
        );
      case 'delete':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M17 4.02L16 3H8L7 4H4v1.484L20 5.5V4l-3 .02zM9 10h1.5v9H9v-9zM13.5 10H15v9h-1.5v-9z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M5 7h14v12.857C19 21.036 18.03 22 16.846 22H7.154A2.155 2.155 0 0 1 5 19.857V7zm1.5 12.857c0 .343.29.643.654.643h9.692c.364 0 .654-.3.654-.643V8.5h-11v11.357z"
            />
          </svg>
        );
      case 'download':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M14.94 9.97L16 11.03l-3.53 3.53-3.53-3.53L10 9.97l1.72 1.72V4h1.5v7.69l1.72-1.72zM3 19.75V16h1.421v2.25H19.58V16H21v3.75H3z"
            />
          </svg>
        );
      case 'drag':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M11 18c0 1.1-.9 2-2 2s-2-.9-2-2 .9-2 2-2 2 .9 2 2zm-2-8c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0-6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm6 4c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" />
          </svg>
        );
      case 'dropdown':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 14.482l-6.247-7.14-1.506 1.317L12 17.519l7.753-8.86-1.506-1.317L12 14.482z"
            />
          </svg>
        );
      case 'edit':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M17.5 3.44L14.94 6 19 10.06l2.56-2.56-4.06-4.06zm1.5 4.5L17.06 6l.44-.44 1.94 1.94-.44.44zM14 6.94l-9.75 9.75v4.06h4.06L18.06 11 14 6.94zM5.75 19.25v-1.94L14 9.06 15.94 11l-8.25 8.25H5.75z"
            />
          </svg>
        );
      case 'enter':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M14.222 5.333V22H2v-2h2.222V2h10v1.111h5.556V20H22v2h-4V5.333h-3.778zM10 11v2h2v-2h-2z" />
          </svg>
        );
      case 'event':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M7 12h4v4H7v-4z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M8.5 2H7v1.5H3v18h18v-18h-4V2h-1.5v1.5h-7V2zm7 4V5h-7v1H7V5H4.5v3.25h15V5H17v1h-1.5zm4 3.75h-15V20h15V9.75z"
            />
          </svg>
        );
      case 'event-attending':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M7 2h1.5v1.5h7V2H17v1.5h4v18H3v-18h4V2zm8.5 3v1H17V5h2.5v3.25h-15V5H7v1h1.5V5h7zm-11 4.75h15V20h-15V9.75zm6.779 6.607l4.071-4-.7-.714-3.721 3.656-1.579-1.55-.7.713 1.928 1.895.35.344.351-.344z"
            />
          </svg>
        );
      case 'exit':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M20.182 3.86L22 4.272v15.454l-1.818.413v.042H20L12 22v-1.818V22h-1v-1.818H3.818v-5.455h1.5v3.955H11V5.318H5.318v3.955h-1.5V3.818H11V2h1v1.818V2l8 1.818h.182v.042zM12 18.681V5.318v13.364zM14 12h1v1h-1v-1zm-4 0l-3.279 3-.503-.548 2.273-2.08H1v-.744h7.491l-2.273-2.08L6.72 9 10 12z"
            />
          </svg>
        );
      case 'eye-hide':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M3.47 19.47l1.06 1.06 3.167-3.166C9.118 18.119 10.552 18.5 12 18.5c3.346 0 6.622-2.036 9.834-6.03l.378-.47-.378-.47c-1.394-1.733-2.8-3.097-4.217-4.086L20.53 4.53l-1.06-1.06-3.167 3.167C14.88 5.88 13.447 5.5 12 5.5c-3.347 0-6.622 2.036-9.835 6.03l-.378.47.378.47c1.394 1.733 2.8 3.097 4.218 4.087L3.47 19.47zm3.992-3.993C6.227 14.655 4.98 13.498 3.72 12 6.54 8.644 9.302 7 12 7c1.052 0 2.114.25 3.185.754l-1.298 1.298a3.5 3.5 0 0 0-4.835 4.835l-1.59 1.59zm1.353.769C9.886 16.75 10.948 17 12 17c2.697 0 5.459-1.644 8.279-5-1.259-1.498-2.506-2.655-3.741-3.477l-1.59 1.59a3.5 3.5 0 0 1-4.835 4.835l-1.298 1.298zm2.404-2.404a2 2 0 0 0 2.623-2.623l-2.623 2.623zm1.562-3.684a2 2 0 0 0-2.623 2.623l2.623-2.623z"
            />
          </svg>
        );
      case 'eye-view':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 15.5a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7zm0-1.5a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"
            />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M2.165 11.53C5.378 7.536 8.653 5.5 12 5.5c3.346 0 6.622 2.036 9.834 6.03l.378.47-.378.47C18.622 16.464 15.346 18.5 12 18.5c-3.347 0-6.622-2.036-9.835-6.03L1.787 12l.378-.47zM12 17c2.697 0 5.459-1.644 8.279-5-2.82-3.356-5.582-5-8.28-5C9.303 7 6.54 8.644 3.72 12c2.82 3.356 5.582 5 8.28 5z"
            />
          </svg>
        );
      case 'facebook':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M20.006 3H3.993A.993.993 0 0 0 3 3.993v16.014c0 .548.445.993.993.993h8.622v-6.96h-2.338v-2.725h2.338V9.309c0-2.325 1.42-3.59 3.494-3.59.993 0 1.847.073 2.096.107v2.43h-1.43c-1.129 0-1.347.536-1.347 1.323v1.736h2.698l-.352 2.724h-2.346V21h4.579a.993.993 0 0 0 .993-.993V3.993A.993.993 0 0 0 20.006 3z"
            />
          </svg>
        );
      case 'favourite':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M20.544 6.829a4.819 4.819 0 0 0-1.787-2.047 4.876 4.876 0 0 0-2.62-.764 4.997 4.997 0 0 0-3.509 1.463c-.216.215-.414.447-.666.714-.27-.285-.486-.553-.737-.785C10.253 4.464 9.137 4 7.913 4a5.047 5.047 0 0 0-1.367.179 4.793 4.793 0 0 0-2.549 1.686A4.726 4.726 0 0 0 3 8.738c-.018 1.446.558 2.66 1.584 3.66a741.535 741.535 0 0 0 5.327 5.282c.684.678 1.367 1.356 2.07 2.07.09-.09.143-.125.197-.178l7.235-7.175a4.66 4.66 0 0 0 .485-.553c1.15-1.553 1.458-3.248.646-5.015zm-1.673 4.265a4.043 4.043 0 0 1-.378.429l-6.424 6.37-.09.09-1.188-1.178-1.852-1.838c-1.134-1.124-2.321-2.284-3.473-3.444-.81-.821-1.206-1.732-1.206-2.767 0-.764.254-1.506.723-2.113a3.507 3.507 0 0 1 1.869-1.242c.346-.092.703-.14 1.061-.143.9 0 1.71.34 2.448 1.053.146.141.284.29.414.446.09.09.18.197.27.286l.917.982.936-.973.252-.268c.144-.16.27-.285.396-.41a3.731 3.731 0 0 1 2.591-1.107c.688.001 1.361.199 1.939.569.578.37 1.035.898 1.319 1.52.574 1.258.412 2.489-.524 3.738z" />
          </svg>
        );
      case 'favourite-filled':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 25"
          >
            <path d="M18.757 5.29c.781.499 1.402 1.21 1.787 2.05.812 1.77.504 3.467-.646 5.022-.147.197-.31.383-.485.554l-7.235 7.186c-.054.053-.108.089-.198.178-.702-.715-1.385-1.394-2.07-2.073a742.63 742.63 0 0 1-5.326-5.29C3.558 11.915 2.982 10.7 3 9.252a4.737 4.737 0 0 1 .997-2.877 4.792 4.792 0 0 1 2.549-1.69 5.04 5.04 0 0 1 1.367-.178c1.224 0 2.34.465 3.312 1.412.251.232.467.5.737.786.252-.268.45-.5.666-.715a4.993 4.993 0 0 1 3.51-1.465 4.87 4.87 0 0 1 2.619.765z" />
          </svg>
        );
      case 'filter':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M3 6.851h2.636v1.76H3zM21 17.412h-2.636v-1.76H21zM8.697 6.851H21v1.76H8.697zM15.303 17.412H3v-1.76h12.303zM7.395 4.211v7.041H5.637v-7.04zM16.606 20.052v-7.04h1.758v7.04z" />
          </svg>
        );
      case 'floorplan':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M8.002 9.558L12.5 7.136l4.498 2.422-4.498 2.768-4.498-2.768zM12.5 6l5.482 2.952L19 9.5l-.984.606L12.5 13.5l-5.516-3.394L6 9.5l1.018-.548L12.5 6zm5.483 5.952L19 12.5l-6.5 4-6.5-4 1.016-.548 5.484 3.374 5.483-3.374zm0 3L19 15.5l-6.5 4-6.5-4 1.016-.548 5.484 3.374 5.483-3.374z"
            />
          </svg>
        );
      case 'follow':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M2 12.052C2 6.501 6.5 2 12.052 2s10.053 4.5 10.053 10.052-4.501 10.053-10.053 10.053C6.501 22.105 2 17.605 2 12.052zM12.052 3.5a8.552 8.552 0 1 0 0 17.105 8.552 8.552 0 0 0 0-17.105zm-.75 7.802v-3.9h1.5v3.9h3.901v1.5h-3.9v3.901h-1.5v-3.9H7.4v-1.5h3.901z"
            />
          </svg>
        );
      case 'fullscreen':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M6.5 10H5V5h5v1.5H6.5V10zM5 14h1.5v3.5H10V19H5v-5zm12.5 3.5H14V19h5v-5h-1.5v3.5zM14 6.5V5h5v5h-1.5V6.5H14z"
            />
          </svg>
        );
      case 'fullscreen-exit':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M8.5 8.5H5V10h5V5H8.5v3.5zM14 14v5h1.5v-3.5H19V14h-5zm5-4h-5V5h1.5v3.5H19V10zm-9 4H5v1.5h3.5V19H10v-5z"
            />
          </svg>
        );
      case 'gallery':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M7.5 5.702L2 4.25v15l5.5-.968V5.702zM6 17.023l-2.5.44V6.197l2.5.66v10.166zM16.5 5.702L22 4.25v15l-5.5-.968V5.702zm4 11.761V6.197l-2.5.66v10.166l2.5.44zM9 5.5h6v13H9v-13zM10.5 7v10h3V7h-3z"
            />
          </svg>
        );
      case 'grid':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M3 3h4v4H3V3zM3 10h4v4H3v-4zM7 17H3v4h4v-4zM10 3h4v4h-4V3zM14 10h-4v4h4v-4zM10 17h4v4h-4v-4zM21 3h-4v4h4V3zM17 10h4v4h-4v-4zM21 17h-4v4h4v-4z" />
          </svg>
        );
      case 'grid-alternative':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M10.714 4a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v5.714a1 1 0 0 0 1 1h5.714a1 1 0 0 0 1-1V4zM21 4a1 1 0 0 0-1-1h-5.714a1 1 0 0 0-1 1v5.714a1 1 0 0 0 1 1H20a1 1 0 0 0 1-1V4zM13.286 14.286a1 1 0 0 1 1-1H20a1 1 0 0 1 1 1V20a1 1 0 0 1-1 1h-5.714a1 1 0 0 1-1-1v-5.714zM10.714 14.286a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1V20a1 1 0 0 0 1 1h5.714a1 1 0 0 0 1-1v-5.714z" />
          </svg>
        );
      case 'guest':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M11.684 11.79a3.684 3.684 0 1 1 0-7.37 3.684 3.684 0 0 1 0 7.37zm0-5.895a2.21 2.21 0 1 0 0 4.421 2.21 2.21 0 0 0 0-4.421zM18.316 20h-1.474v-3.79a2.21 2.21 0 0 0-2.21-2.21H8.737a2.21 2.21 0 0 0-2.21 2.21V20H5.052v-3.79a3.685 3.685 0 0 1 3.684-3.684h5.895a3.684 3.684 0 0 1 3.684 3.685V20z" />
          </svg>
        );
      case 'guest-add':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M10.085 11.79a3.684 3.684 0 1 1 0-7.37 3.684 3.684 0 0 1 0 7.37zm0-5.895a2.21 2.21 0 1 0 0 4.42 2.21 2.21 0 0 0 0-4.42zM16.716 20h-1.473v-3.79a2.21 2.21 0 0 0-2.21-2.21H7.136a2.21 2.21 0 0 0-2.21 2.21V20H3.453v-3.79a3.685 3.685 0 0 1 3.684-3.684h5.895a3.684 3.684 0 0 1 3.684 3.685V20zM18.4 3.2v5.6h-.8V3.2h.8z" />
            <path d="M15.2 5.6h5.6v.8h-5.6v-.8z" />
          </svg>
        );
      case 'guest-added':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M6.5 7.718a4.503 4.503 0 0 0 4.5 4.507c2.485 0 4.5-2.018 4.5-4.507A4.503 4.503 0 0 0 11 3.212a4.503 4.503 0 0 0-4.5 4.506zm7.5 0a3.002 3.002 0 0 1-3 3.005c-1.657 0-3-1.345-3-3.005a3.002 3.002 0 0 1 3-3.004c1.657 0 3 1.345 3 3.004zM4.5 18.735H11v1.502H3v-2.003a5.004 5.004 0 0 1 5-5.008h6c2.761 0 5 2.242 5 5.008v2.003h-1.5v-2.003a3.503 3.503 0 0 0-3.5-3.505H8c-1.933 0-3.5 1.57-3.5 3.505v.5zM17 7.718a4.507 4.507 0 0 1-3.5 4.395A4.503 4.503 0 0 0 19 7.718a4.503 4.503 0 0 0-5.5-4.395A4.507 4.507 0 0 1 17 7.718zm6 12.519h-2v-2.01a5 5 0 0 0-5-5h2a5 5 0 0 1 5 5v2.01z"
            />
            <path d="M1 10.222h5v1.002H1v-1.002z" />
            <path d="M4 8.219v5.008H3V8.218h1z" />
          </svg>
        );
      case 'guest-added-alternative':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M14.084 11.79a3.685 3.685 0 1 1 0-7.37 3.685 3.685 0 0 1 0 7.37zm0-5.895a2.21 2.21 0 1 0 0 4.421 2.21 2.21 0 0 0 0-4.421zM20.716 20h-1.473v-3.79a2.21 2.21 0 0 0-2.21-2.21h-5.896a2.21 2.21 0 0 0-2.21 2.21V20H7.453v-3.79a3.685 3.685 0 0 1 3.684-3.684h5.895a3.684 3.684 0 0 1 3.684 3.685V20zM6.4 3.2v5.6h-.8V3.2h.8z" />
            <path d="M3.2 5.6h5.6v.8H3.2v-.8z" />
          </svg>
        );
      case 'headphones':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M20.5 12a8.5 8.5 0 1 1-17 0 8.5 8.5 0 0 1 17 0zm1.5 0c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2s10 4.477 10 10zm-8.333.6h2.777v-1.65c0-2.43-1.99-4.4-4.444-4.4-2.455 0-4.444 1.97-4.444 4.4v1.65h2.777V17H8.667A1.655 1.655 0 0 1 7 15.35v-4.4C7 8.216 9.239 6 12 6s5 2.216 5 4.95v4.4c0 .911-.746 1.65-1.667 1.65h-1.666v-4.4z"
            />
          </svg>
        );
      case 'help':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M13 16v2h-2v-2h2zM8 10c0-2.21 1.79-4 4-4s4 1.79 4 4c0 1.283-.79 1.973-1.56 2.646C13.712 13.283 13 13.905 13 15h-2c0-1.821.942-2.543 1.77-3.178.65-.498 1.23-.943 1.23-1.822 0-1.1-.9-2-2-2s-2 .9-2 2H8z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10zm8.5-10a8.5 8.5 0 1 1-17 0 8.5 8.5 0 0 1 17 0z"
            />
          </svg>
        );
      case 'home':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12.353 5.226l-.512-.479-.512.479-8.075 7.547L4.28 13.87l1.429-1.336v8.357h12.266v-8.357l1.43 1.336 1.024-1.096L16.5 9.102V6.078h-3.234l-.913-.852zm1.982 1.852L15.5 8.167V7.078h-1.165zm2.14 4.053L11.84 6.8l-4.633 4.33v8.259h9.266v-8.26z"
            />
          </svg>
        );
      case 'hotel':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M7 13c1.66 0 3-1.34 3-3S8.66 7 7 7s-3 1.34-3 3 1.34 3 3 3zm12-6h-8v7H3V5H1v15h2v-3h18v3h2v-9c0-2.21-1.79-4-4-4z" />
          </svg>
        );
      case 'hotel-alternative':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M17.037 17.212A6.833 6.833 0 0 1 12.429 19C8.624 19 5.5 15.86 5.5 11.938a7.087 7.087 0 0 1 3.211-5.96 10.28 10.28 0 0 0-.081 1.29c0 5.014 3.63 9.201 8.407 9.944zm1.18-1.39c-4.497-.182-8.087-3.942-8.087-8.555 0-.716.087-1.413.25-2.078.145-.59.35-1.155.608-1.689a8.268 8.268 0 0 0-1.838.547C6.124 5.347 4 8.39 4 11.937c0 4.73 3.774 8.563 8.429 8.563 2.647 0 5.01-1.24 6.555-3.18A8.588 8.588 0 0 0 20 15.705a8.36 8.36 0 0 1-1.784.118z"
            />
          </svg>
        );
      case 'info':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M11.5 10.75h-.75v-1.5H13v6.5h1.75v1.5h-5v-1.5h1.75v-5zM13 7a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M22 12c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2s10 4.477 10 10zm-10 8.5a8.5 8.5 0 1 0 0-17 8.5 8.5 0 0 0 0 17z"
            />
          </svg>
        );
      case 'instagram':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M17.879 7.2a1.08 1.08 0 1 1-2.16 0 1.08 1.08 0 0 1 2.16 0z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M11.997 7.383a4.62 4.62 0 1 0 0 9.24 4.62 4.62 0 0 0 0-9.24zm0 7.62a2.999 2.999 0 1 1 0-5.999 2.999 2.999 0 0 1 0 5.998z"
            />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M8.288 3.06c.96-.044 1.266-.054 3.71-.054 2.443 0 2.749.01 3.709.054.957.044 1.611.196 2.184.418a4.41 4.41 0 0 1 1.593 1.038c.5.5.808 1.002 1.038 1.594.222.572.375 1.226.418 2.183.044.96.054 1.267.054 3.71 0 2.444-.01 2.75-.054 3.71-.044.957-.196 1.611-.418 2.184a4.41 4.41 0 0 1-1.038 1.593c-.5.5-1.002.808-1.593 1.038-.573.222-1.227.374-2.184.418-.96.044-1.266.054-3.71.054-2.443 0-2.75-.01-3.71-.054-.957-.044-1.611-.196-2.183-.418A4.411 4.411 0 0 1 4.51 19.49a4.41 4.41 0 0 1-1.038-1.593c-.222-.573-.374-1.227-.418-2.184-.044-.96-.054-1.266-.054-3.71 0-2.443.01-2.75.054-3.71.044-.957.196-1.611.418-2.183A4.41 4.41 0 0 1 4.51 4.516a4.41 4.41 0 0 1 1.594-1.038c.572-.222 1.226-.374 2.184-.418zm7.345 1.62c-.949-.044-1.233-.053-3.636-.053-2.402 0-2.687.01-3.635.052-.878.04-1.354.187-1.671.31-.42.163-.72.358-1.035.673-.314.315-.51.615-.673 1.035-.123.317-.27.793-.31 1.67-.043.95-.052 1.234-.052 3.636s.01 2.687.053 3.636c.04.877.186 1.353.31 1.67.163.42.358.72.672 1.035.315.315.615.51 1.035.673.317.123.793.27 1.67.31.95.043 1.234.052 3.636.052 2.403 0 2.687-.01 3.636-.052.877-.04 1.353-.187 1.67-.31.42-.163.72-.358 1.035-.673.315-.315.51-.615.673-1.035.123-.317.27-.793.31-1.67.043-.95.052-1.234.052-3.636s-.009-2.687-.052-3.636c-.04-.877-.187-1.353-.31-1.67a2.788 2.788 0 0 0-.673-1.035 2.787 2.787 0 0 0-1.035-.673c-.317-.123-.793-.27-1.67-.31z"
            />
          </svg>
        );
      case 'institution':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M17 2.5H7V11H3v10h18V11h-4V2.5zM15.5 11V8.25h-2.75V11h2.75zm-2.75 1.5h2.75v2.75h-2.75V12.5zm-1.5-1.5V8.25H8.5V11h2.75zM8.5 12.5h2.75v2.75H8.5V12.5zm-1.5 0H4.5v7H7v-7zm1.5 7h2.75v-2.75H8.5v2.75zm4.25 0h2.75v-2.75h-2.75v2.75zm4.25 0v-7h2.5v7H17zM15.5 6.75V4h-2.75v2.75h2.75zm-4.25 0V4H8.5v2.75h2.75z"
            />
          </svg>
        );
      case 'key':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M9.93 12.75A4.001 4.001 0 0 1 2 12a4 4 0 0 1 7.93-.75H21.5v1.5h-2.25v2.776h-1.5V12.75h-1.5v2.776h-1.5V12.75H9.93zM8.5 12a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"
            />
          </svg>
        );
      case 'link':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M5.106 18.894a4.75 4.75 0 0 1 0-6.717l2.828-2.829 1.06 1.061-2.828 2.829a3.25 3.25 0 1 0 4.597 4.596l2.828-2.829 1.06 1.061-2.828 2.828a4.75 4.75 0 0 1-6.717 0zm10.253-9.192l-5.657 5.657-1.06-1.06 5.656-5.658 1.06 1.061zm-4.95-.707l2.828-2.828a3.25 3.25 0 0 1 4.597 4.596l-2.829 2.828 1.06 1.06 2.83-2.828a4.75 4.75 0 0 0-6.718-6.717L9.348 7.934l1.061 1.06z"
            />
          </svg>
        );
      case 'linkarrow':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M13.746 11.865L7.238 5.357 8.865 3.73l6.508 6.508L17 11.865 8.865 20l-1.627-1.627 6.508-6.508z"
            />
          </svg>
        );
      case 'linkbroken':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M3.47 19.47l1.06 1.06 3.78-3.78H11v-1.5H9.81l2.5-2.5H16v-1.5h-2.19l2.5-2.5H17a3.25 3.25 0 0 1 0 6.5h-4v1.5h4a4.75 4.75 0 0 0 .752-9.44l2.778-2.78-1.06-1.06-3.78 3.78H13v1.5h1.19l-2.5 2.5H8v1.5h2.19l-2.5 2.5H7a3.25 3.25 0 0 1 0-6.5h4v-1.5H7a4.75 4.75 0 0 0-.752 9.44L3.47 19.47z"
            />
          </svg>
        );
      case 'linkedIn':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M18.339 18.338h-2.67v-4.177c0-.996-.017-2.278-1.387-2.278-1.39 0-1.601 1.086-1.601 2.207v4.248h-2.667v-8.59h2.56v1.175h.036c.356-.676 1.227-1.388 2.526-1.388 2.703 0 3.203 1.779 3.203 4.092v4.711zM7.004 8.575a1.548 1.548 0 1 1-.003-3.096 1.548 1.548 0 0 1 .003 3.096zm-1.337 9.763H8.34v-8.59H5.667v8.59zM19.67 3H4.328C3.595 3 3 3.581 3 4.298v15.403c0 .718.595 1.3 1.328 1.3h15.34c.735 0 1.332-.582 1.332-1.3V4.298C21 3.581 20.402 3 19.669 3z"
            />
          </svg>
        );
      case 'list':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M4 10.5c-.83 0-1.5.67-1.5 1.5s.67 1.5 1.5 1.5 1.5-.67 1.5-1.5-.67-1.5-1.5-1.5zm0-6c-.83 0-1.5.67-1.5 1.5S3.17 7.5 4 7.5 5.5 6.83 5.5 6 4.83 4.5 4 4.5zm0 12c-.83 0-1.5.68-1.5 1.5s.68 1.5 1.5 1.5 1.5-.68 1.5-1.5-.67-1.5-1.5-1.5zM7 19h14v-2H7v2zm0-6h14v-2H7v2zm0-8v2h14V5H7z" />
          </svg>
        );
      case 'list-alternative':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M8 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM8 12a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM7 17a1 1 0 1 0 0-2 1 1 0 0 0 0 2zM10 7h8v2h-8V7zM18 11h-8v2h8v-2zM10 15h8v2h-8v-2z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M3 4a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4zm1.5 15.5v-15h15v15h-15z"
            />
          </svg>
        );
      case 'live-chat':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M21 6h-2v9H6v2c0 .55.45 1 1 1h11l4 4V7c0-.55-.45-1-1-1zm-4 6V3c0-.55-.45-1-1-1H3c-.55 0-1 .45-1 1v14l4-4h10c.55 0 1-.45 1-1z" />
          </svg>
        );
      case 'locate':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M21 3L3 10.53v.98l6.84 2.65L12.48 21h.98L21 3z" />
          </svg>
        );
      case 'lock':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M17 7v1h3v14H4V8h3V7c0-2.76 2.24-5 5-5s5 2.24 5 5zm-5-3.5C10 3.5 8.5 5 8.5 7v1h7V7c0-2-1.5-3.5-3.5-3.5zm-6.5 17v-11h13v11h-13zM14 15c0 1.1-.9 2-2 2s-2-.9-2-2 .9-2 2-2 2 .9 2 2z"
            />
          </svg>
        );
      case 'mail':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M19.309 5.5H4.69L12 11.996 19.309 5.5zM3.5 6.448V17a.5.5 0 0 0 .5.5h16a.5.5 0 0 0 .5-.5V6.448l-8.002 7.113-.498.443-.498-.443L3.5 6.448zM2 6a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6z"
            />
          </svg>
        );
      case 'map':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M20.25 4.287v13.22l-5.784 2.315-3.966-1.983-5.75 2.875V7.492l5.784-2.313L14.5 7.162l5.75-2.875zM14 8.589v9.323l-3-1.5V7.089l3 1.5zm1 9.403V8.59l3.75-1.875v9.778l-3.75 1.5zm-5-1.58V7.008l-3.75 1.5v9.779L10 16.412z"
            />
          </svg>
        );
      case 'menu':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M4.615 6.462h14.769v1.641H4.615zM4.615 11.385h14.769v1.641H4.615zM4.615 16.309h14.769v1.641H4.615z" />
          </svg>
        );
      case 'move':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M3 6a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6zm1.5 13.5v-13h15v13h-15z"
            />
            <path d="M12.507 17.105l4.603-4.052L12.507 9l-1.013 1.105 2.578 2.198H7v1.5h7.072L11.494 16l1.013 1.105zM12 5.02L11 4H4L3 5v1.484L15 6.5V5l-3 .02z" />
          </svg>
        );
      case 'note':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 10.128L18.12 4l2.76 2.765-6.119 6.128H12v-2.765zm1.02.423v1.32h1.319l5.1-5.106-1.32-1.32-5.1 5.106zM6.5 7.5H13V6H5v13h13v-6h-1.5v4.5h-10v-10z"
            />
          </svg>
        );
      case 'organise':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M21.5 2.25H8v13.5h13.5V2.25zm-12 12V3.75H20v10.5H9.5zm-5.75-7h3v1.5H4.5v10.5H15V17h1.5v3.75H3V7.25h.75z"
            />
          </svg>
        );
      case 'ovr-list':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M8 8.5v1h8v-1H8zM16 14.5v1H8v-1h8zM8 12.5h8v-1H8v1z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M22 12c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2s10 4.477 10 10zm-1.5 0a8.5 8.5 0 1 1-17 0 8.5 8.5 0 0 1 17 0z"
            />
          </svg>
        );
      case 'pause':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M20.5 12a8.5 8.5 0 1 1-17 0 8.5 8.5 0 0 1 17 0zm1.5 0c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2s10 4.477 10 10zm-11 4H9V8h2v8zm4 0h-2V8h2v8z"
            />
          </svg>
        );
      case 'pause-alternative':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z" />
          </svg>
        );
      case 'pin':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 6c-2.25 0-4 1.875-4 4s1.875 4 4 4 4-1.875 4-4-1.75-4-4-4zm-2.5 4c0-1.327 1.109-2.5 2.5-2.5s2.5 1.173 2.5 2.5c0 1.297-1.203 2.5-2.5 2.5S9.5 11.297 9.5 10z"
            />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M20 10.128C20 17.16 12 22 12 22s-8-4.84-8-11.872C4 5.653 7.596 2 12 2s8 3.653 8 8.128zm-1.5 0c0 2.945-1.688 5.556-3.584 7.536A21.393 21.393 0 0 1 12 20.19a21.393 21.393 0 0 1-2.916-2.528c-1.896-1.98-3.584-4.59-3.584-7.535C5.5 6.458 8.446 3.5 12 3.5s6.5 2.959 6.5 6.628z"
            />
          </svg>
        );
      case 'play':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M16.889 12l-8.556 4.889V7.11L16.89 12z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1 1 5.925 1 12s4.925 11 11 11zm9.778-11c0 5.4-4.378 9.778-9.778 9.778S2.222 17.4 2.222 12 6.6 2.222 12 2.222 21.778 6.6 21.778 12z"
            />
          </svg>
        );
      case 'playback':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M8 4L13.25.536V3.08A10 10 0 1 1 2 13h1.5a8.5 8.5 0 1 0 9.75-8.407v2.871L8 4zm7.626 6.956h-.352v-.8h.76v.6c0 .52-.144.96-.528 1.304l-.336-.24c.304-.28.424-.52.456-.864zm.904 0v-.8h.76v.6c0 .52-.144.96-.528 1.304l-.336-.24c.304-.28.424-.52.456-.864h-.352zm-4.082 4.656c1.472 0 2.08-1.128 2.08-2.92v-.128c0-1.464-.576-2.384-2.08-2.384-1.496 0-2.072.92-2.072 2.384v.128c0 1.792.608 2.92 2.072 2.92zm0-.64c-1.056 0-1.408-.952-1.408-2.224v-.192c0-.984.224-1.776 1.408-1.776 1.192 0 1.408.792 1.408 1.776v.192c0 1.272-.344 2.224-1.408 2.224zm-3.162.528l-.008-5.2h-.656l-.912.84.368.408.544-.52.008 4.472h.656z"
            />
          </svg>
        );
      case 'playlist':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M4 6H2v14c0 1.1.9 2 2 2h14v-2H4V6zm16-4H8c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-1 9H9V9h10v2zm-4 4H9v-2h6v2zm4-8H9V5h10v2z" />
          </svg>
        );
      case 'recommendation':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M11.801 2.995a3.153 3.153 0 0 1 3.153 3.153v1.984c0 .405.358.717.76.66l1.725-.241c2.512-.352 4.482 2.118 3.58 4.489l-1.452 3.815a3.335 3.335 0 0 1-3.117 2.15H5.615a2.001 2.001 0 0 1-2-2.002V11c0-1.105.895-2.001 2-2.001h3.59l.74-1.481c.2-.398.26-.851.173-1.287l-.19-.951a1.91 1.91 0 0 1 1.873-2.285zm1.819 3.153a1.819 1.819 0 0 0-1.819-1.819.576.576 0 0 0-.565.69l.19.95a3.335 3.335 0 0 1-.287 2.146l-.854 1.708v7.847h6.165c.83 0 1.575-.513 1.87-1.29l1.452-3.814c.541-1.423-.64-2.905-2.148-2.694l-1.725.242a2.001 2.001 0 0 1-2.279-1.982V6.148zm-4.67 4.185H5.616a.667.667 0 0 0-.667.667v6.003c0 .369.299.667.667.667h3.336v-7.337z"
            />
          </svg>
        );
      case 'redirect':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M8.79 7.649l6.924-.064-10.266 9.998 1.033.95L16.857 8.6l-.044 6.721h1.495l.066-9.194-9.607.063.022 1.459z"
            />
          </svg>
        );
      case 'refresh':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M9.988 5.035a7.25 7.25 0 0 1 8.29 10.59l-.028-1.638-1.5.026.072 4.249 4.264-.072-.025-1.5-1.693.029A8.75 8.75 0 0 0 9.572 3.593l.416 1.442zM4.823 10.973a7.25 7.25 0 0 1 1.555-3.55V9.05h1.5V4.8H3.613v1.5h1.748a8.75 8.75 0 0 0 9.93 13.806l-.564-1.39a7.25 7.25 0 0 1-9.904-7.744z" />
          </svg>
        );
      case 'reply':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M14 9V5l7 7-7 7v-4.1c-5 0-8.5 1.6-11 5.1 1-5 4-10 11-11z" />
          </svg>
        );
      case 'report':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M19 3h-4.18C14.4 1.84 13.3 1 12 1c-1.3 0-2.4.84-2.82 2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 0c.55 0 1 .45 1 1s-.45 1-1 1-1-.45-1-1 .45-1 1-1zm-2 14l-4-4 1.41-1.41L10 14.17l6.59-6.59L18 9l-8 8z" />
          </svg>
        );
      case 'report-alternative':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M14 2H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm2 16H8v-2h8v2zm0-4H8v-2h8v2zm-3-5V3.5L18.5 9H13z" />
          </svg>
        );
      case 'restaurant':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M4 9c0 .57.036 1.068.112 1.5C4.434 12.344 5.475 13 7.5 13v9H9v-9c2.025 0 3.066-.656 3.388-2.5.076-.432.112-.93.112-1.5V2H11v7H9V2H7.5v7h-2V2H4v7zm6.573 2.122c.089-.1.198-.282.283-.622H5.644c.085.34.194.522.283.622.134.148.47.378 1.573.378H9c1.103 0 1.439-.23 1.573-.378zM20 2c-.523 0-1.026.08-1.5.222C16.472 2.831 15 4.573 15 6v8h3.5v8H20V2zm-2.556 2.476a4.118 4.118 0 0 1 1.056-.66V12.5h-2V6c0-.291.234-.911.944-1.524z"
            />
          </svg>
        );
      case 'room-view':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M5.943 5L3.491 2.5h17.037L18.076 5l.7.714 2.72-2.774c.003.02.004.04.004.06v17.49L19.058 18l-.7.714 2.726 2.78A.508.508 0 0 1 21 21.5H3a.505.505 0 0 1-.084-.007l2.726-2.78-.7-.713L2.5 20.49V3c0-.026.002-.052.006-.076l2.737 2.79.7-.714zM1 3a2 2 0 0 1 2-2h18a2 2 0 0 1 2 2v18a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V3zm8 6h6v6H9V9zM8 9a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V9z"
            />
          </svg>
        );
      case 'search':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M15.596 14.535a6.5 6.5 0 1 0-1.06 1.06L19 20.062l1.06-1.06-4.465-4.466zM15.5 10.5a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"
            />
          </svg>
        );
      case 'settings':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M18 12c0 .27-.02.53-.05.78l1.67 1.32c.16.12.2.33.1.51l-1.6 2.77c-.1.18-.31.25-.49.18l-1.99-.8c-.41.31-.86.58-1.35.78l-.3 2.12c-.02.2-.19.34-.39.34h-3.2c-.2 0-.36-.14-.4-.34l-.3-2.12c-.49-.2-.93-.46-1.35-.78l-1.99.8c-.18.06-.39 0-.49-.18l-1.6-2.77a.413.413 0 0 1 .1-.51l1.69-1.32C6.02 12.53 6 12.26 6 12s.03-.53.07-.78L4.38 9.9a.388.388 0 0 1-.1-.51l1.6-2.77c.1-.18.31-.25.49-.18l1.99.8c.41-.31.86-.58 1.35-.78l.3-2.12c.03-.2.19-.34.39-.34h3.2c.2 0 .37.14.4.34l.3 2.12c.49.2.93.46 1.35.78l1.99-.8c.18-.06.39 0 .49.18l1.6 2.77c.09.17.05.39-.1.51l-1.69 1.32c.04.25.06.51.06.78zm-9 0c0 1.65 1.35 3 3 3s3-1.35 3-3-1.35-3-3-3-3 1.35-3 3z"
            />
          </svg>
        );
      case 'share':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M8.47 6.47l1.06 1.06 1.72-1.72v7.69h1.5V5.81l1.72 1.72 1.06-1.06L12 2.94 8.47 6.47z" />
            <path d="M3.25 7v13.75h17.5V7h-1.5v12.25H4.75V7h-1.5z" />
          </svg>
        );
      case 'sorting':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M12.5 8.57l-3.5 3h7l-3.5-3zM12.5 17.57l3.5-3H9l3.5 3z" />
          </svg>
        );
      case 'subtitle':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M20 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zM4 12h11.5v2H4v-2zm0 6h5v-2H4v2zm16 0h-9v-2h9v2zm-2.5-4H20v-2h-2.5v2z"
            />
          </svg>
        );
      case 'telephone':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M16.34 16.447L14.88 18.6c1.452.507 3.003.805 4.619.856v-2.491a12.915 12.915 0 0 1-3.16-.518zm-5.56 1.803a17.088 17.088 0 0 1-5.785-6.286 16.893 16.893 0 0 1-1.995-8c0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02L6 10.464c.29.678.619 1.318.984 1.921a13.44 13.44 0 0 0 4.595 4.595c.603.366 1.243.694 1.921.984l1.91-2.82c.2-.19.45-.29.71-.29.1 0 .21.01.31.05 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1v3.49c0 .55-.45 1-1 1a16.96 16.96 0 0 1-9.22-2.714zM5.365 9.083l2.161-1.464a12.848 12.848 0 0 1-.516-3.155H4.508a15.48 15.48 0 0 0 .856 4.619z"
            />
          </svg>
        );
      case 'ticket':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M21 10.6V6a1 1 0 0 0-.86-1H3.86A1 1 0 0 0 3 6v4.6c.94 0 1.7 0 1.7 1.4S4 13.4 3 13.4v4.67a1 1 0 0 0 .86.93h16.28a1 1 0 0 0 .86-.93V13.4c-.94 0-1.71 0-1.71-1.4s.77-1.4 1.71-1.4zm-1.5-1.33c-.157.05-.308.117-.45.2A2.71 2.71 0 0 0 17.79 12a2.711 2.711 0 0 0 1.26 2.53c.142.083.293.15.45.2v2.77h-15v-2.77c.157-.05.308-.117.45-.2A2.71 2.71 0 0 0 6.21 12 2.71 2.71 0 0 0 5 9.47a2.86 2.86 0 0 0-.44-.2V6.5h15l-.06 2.77z"
            />
          </svg>
        );
      case 'time':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M13.25 14.25V8h-1.5v4.75H8v1.5h5.25z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10zm8.5-10a8.5 8.5 0 1 1-17 0 8.5 8.5 0 0 1 17 0z"
            />
          </svg>
        );
      case 'twitter':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M8.731 19.144c6.885 0 10.653-5.443 10.653-10.156 0-.153 0-.306-.008-.459a7.44 7.44 0 0 0 1.87-1.851 7.879 7.879 0 0 1-2.154.563 3.627 3.627 0 0 0 1.65-1.976 7.672 7.672 0 0 1-2.38.863A3.824 3.824 0 0 0 15.63 5c-2.066 0-3.745 1.6-3.745 3.57 0 .28.036.55.094.815-3.11-.146-5.87-1.573-7.717-3.73A3.443 3.443 0 0 0 3.76 7.45c0 1.24.665 2.332 1.665 2.972a3.929 3.929 0 0 1-1.694-.445v.049c0 1.726 1.292 3.174 3 3.5a3.82 3.82 0 0 1-.985.126c-.24 0-.474-.02-.7-.063.474 1.42 1.861 2.45 3.497 2.478A7.745 7.745 0 0 1 3.89 17.6c-.3 0-.599-.014-.891-.049a11.033 11.033 0 0 0 5.731 1.594z"
            />
          </svg>
        );
      case 'unlock':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 3.5c-.925 0-1.766.359-2.392.945l-.764-1.323A5 5 0 0 1 17 7v1h3v14H4V8h11.5V7A3.5 3.5 0 0 0 12 3.5zm-6.5 6h13v11h-13v-11zM14 15a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"
            />
          </svg>
        );
      case 'vip':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M2.5 18.5v-13h19v13h-19zM1 5a1 1 0 0 1 1-1h20a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V5zm13.204 4.094A16.89 16.89 0 0 1 15.939 9C17.605 9 18 9.764 18 10.88c0 1.598-.85 2.062-2.121 2.062h-.447v1.735h-1.228V9.094zm1.228 2.843h.447c.566 0 .91-.249.91-1.039 0-.532-.172-.859-.807-.867-.206 0-.378.008-.55.025v1.881zM9.572 9.07c-.3 1.254-.67 2.722-1.056 4.19a160.832 160.832 0 0 1-1.21-4.19H6c.575 1.906 1.142 3.77 1.76 5.608h1.538a165.938 165.938 0 0 0 1.572-5.608H9.573zm2.125 5.608h1.27V9.069h-1.27v5.608z"
            />
          </svg>
        );
      case 'vip-card':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M2 5a1 1 0 0 1 1-1h18a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5zm1.5 8.692V5.5h17v6.354l-17 1.838zm0 1.508v3.3h17v-5.137L3.5 15.2z"
            />
          </svg>
        );
      case 'volume':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M14 5.29V3.23c4.01.91 7 4.49 7 8.77 0 4.28-2.99 7.86-7 8.77v-2.06c2.89-.86 5-3.54 5-6.71s-2.11-5.85-5-6.71zM3 9v6h4l5 5V4L7 9H3z" />
            <path d="M16.5 12A4.5 4.5 0 0 0 14 7.97v8.05c1.48-.73 2.5-2.25 2.5-4.02z" />
          </svg>
        );
      case 'warning':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 4l9 16H3l9-16zm6.435 14.5H5.565L12 7.06l6.435 11.44zM11.5 12h1v3h-1v-3zm1 4v1h-1v-1h1z"
            />
          </svg>
        );
      case 'web':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M2 4h20v16H2V4zm1.5 1.5h17v2.75h-17V5.5zm0 4.25v8.75h17V9.75h-17z"
            />
          </svg>
        );
      case 'weebo':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M16.949 3.507a5.262 5.262 0 0 0-1.355.104.775.775 0 0 0-.598.912.775.775 0 0 0 .911.599 3.782 3.782 0 0 1 3.594 1.146 3.793 3.793 0 0 1 .781 3.698.765.765 0 0 0 .495.963c.4.13.833-.094.964-.495.56-1.741.221-3.727-1.094-5.182a5.33 5.33 0 0 0-3.698-1.745zm-6.902 2.292c-1.396.15-3.346 1.237-5.078 2.969C3.084 10.656 2 12.664 2 14.393c0 3.307 4.235 5.313 8.386 5.313 5.44 0 9.063-3.168 9.063-5.678 0-1.517-1.273-2.38-2.422-2.734l-.04-.012c-.262-.077-.438-.13-.299-.483.32-.804.371-1.51.026-2.005-.647-.928-2.444-.88-4.48-.026 0 0-.63.3-.468-.209.313-1.006.254-1.855-.234-2.344-.345-.345-.85-.485-1.485-.416zm6.12.469c.218-.046.43-.062.651-.053.665.03 1.319.33 1.797.86.642.71.82 1.68.547 2.526a.66.66 0 0 1-.833.417.662.662 0 0 1-.417-.834 1.243 1.243 0 0 0-.26-1.224 1.307 1.307 0 0 0-1.224-.39.651.651 0 0 1-.782-.495.69.69 0 0 1 .521-.807zm-5.338 4.349c2.767.097 4.993 1.484 5.182 3.385.215 2.175-2.288 4.206-5.6 4.532-3.31.325-6.19-1.185-6.406-3.36C3.79 13 6.32 10.968 9.631 10.643c.413-.043.804-.04 1.198-.026zM6.688 14.08c.514-1.041 1.64-1.735 2.838-1.849.4-.039.805.004 1.198.105 1.631.42 2.465 1.943 1.797 3.437-.677 1.53-2.62 2.354-4.27 1.823-1.593-.514-2.26-2.1-1.563-3.515zm3.594-.026a.3.3 0 0 1 .13.027.339.339 0 0 1 .182.494.479.479 0 0 1-.573.209c-.198-.082-.267-.3-.156-.495a.51.51 0 0 1 .417-.235zm-1.12.547a1.128 1.128 0 0 0-.417-.078c-.417-.006-.83.228-1.068.6-.319.497-.169 1.096.339 1.327.518.235 1.191-.01 1.51-.52.316-.515.153-1.107-.364-1.329z"
            />
          </svg>
        );
      case 'whatsapp':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M3 21.086l1.271-4.644a8.943 8.943 0 0 1-1.196-4.481C3.078 7.02 7.098 3 12.038 3c2.397 0 4.647.934 6.34 2.628A8.91 8.91 0 0 1 21 11.97c-.002 4.941-4.023 8.962-8.962 8.962-1.5-.001-2.978-.377-4.287-1.091L3 21.085zm4.971-2.869c1.263.75 2.47 1.199 4.064 1.2 4.105 0 7.45-3.342 7.452-7.45a7.447 7.447 0 0 0-7.446-7.454c-4.109 0-7.451 3.342-7.452 7.449-.001 1.676.49 2.932 1.315 4.245l-.753 2.75 2.82-.74zm8.581-4.117c-.055-.094-.205-.15-.43-.262-.223-.112-1.324-.654-1.53-.729-.205-.074-.354-.112-.504.113-.149.223-.579.728-.709.878-.13.149-.261.168-.485.055-.224-.112-.946-.348-1.801-1.111-.666-.594-1.116-1.327-1.246-1.552-.13-.224-.014-.345.098-.457.101-.1.224-.261.336-.392.114-.13.15-.223.226-.373.075-.15.038-.28-.019-.393-.056-.111-.504-1.214-.69-1.662-.182-.437-.367-.378-.504-.385l-.43-.007a.82.82 0 0 0-.596.28c-.205.225-.784.766-.784 1.868 0 1.103.802 2.168.914 2.317.112.15 1.579 2.411 3.825 3.381.534.23.952.369 1.277.472.536.17 1.024.146 1.41.089.43-.064 1.325-.542 1.512-1.065.187-.524.187-.972.13-1.065z" />
          </svg>
        );
      case 'world':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10zm7.502-6A8.499 8.499 0 0 1 12 20.5 8.499 8.499 0 0 1 4.498 16h15.004zm.624-1.5H3.874A8.498 8.498 0 0 1 3.5 12c0-1.056.193-2.067.545-3h15.91a8.48 8.48 0 0 1 .545 3c0 .87-.13 1.71-.374 2.5zM12 3.5a8.494 8.494 0 0 0-7.212 4h14.424A8.494 8.494 0 0 0 12 3.5z"
            />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M13.795 18.514c.796-1.592 1.33-3.895 1.33-6.514 0-2.62-.534-4.922-1.33-6.514-.4-.8-.83-1.347-1.211-1.67C12.209 3.5 12.012 3.5 12 3.5c-.011 0-.21 0-.584.317-.381.322-.81.869-1.21 1.669C9.408 7.078 8.874 9.381 8.874 12c0 2.62.534 4.922 1.33 6.514.4.8.83 1.347 1.211 1.67.375.316.572.316.584.316.011 0 .21 0 .584-.317.381-.322.81-.869 1.21-1.669zM12 22c2.761 0 5-4.477 5-10S14.761 2 12 2 7 6.477 7 12s2.239 10 5 10z"
            />
          </svg>
        );
      case 'youtube':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M9.955 14.819V8.872l5.227 2.973-5.227 2.974zM21.582 7a2.513 2.513 0 0 0-1.768-1.78C18.254 4.8 12 4.8 12 4.8s-6.254 0-7.814.42A2.513 2.513 0 0 0 2.418 7C2 8.57 2 11.845 2 11.845s0 3.275.418 4.845c.23.866.908 1.549 1.768 1.78 1.56.42 7.814.42 7.814.42s6.254 0 7.814-.42a2.513 2.513 0 0 0 1.768-1.78C22 15.12 22 11.845 22 11.845S22 8.57 21.582 7z"
            />
          </svg>
        );
      case 'zoomin':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path d="M11 7.792h-1v3.004H7v1.002h3v3.004h1v-3.004h3v-1.002h-3V7.792z" />
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M17 11.297a6.488 6.488 0 0 1-1.404 4.041l4.965 4.973-1.06 1.062-4.966-4.973a6.467 6.467 0 0 1-4.035 1.407c-3.59 0-6.5-2.915-6.5-6.51 0-3.595 2.91-6.51 6.5-6.51s6.5 2.915 6.5 6.51zm-6.5 5.007c2.761 0 5-2.242 5-5.007a5.004 5.004 0 0 0-5-5.008c-2.761 0-5 2.242-5 5.008a5.004 5.004 0 0 0 5 5.007z"
            />
          </svg>
        );
      case 'zoomout':
        return (
          <svg
            {...rest}
            data-testid="mch-icon"
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M10.5 15.5a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm6.5-5a6.473 6.473 0 0 1-1.404 4.035l4.965 4.966-1.06 1.06-4.966-4.965A6.5 6.5 0 1 1 17 10.5zM7 10h7v1H7v-1z"
            />
          </svg>
        );
    }
  };

  return getIcon(name);
};

Icon.propTypes = {
  className: PropTypes.string,
  color: PropTypes.string,
  height: PropTypes.number,
  width: PropTypes.number,
  name: PropTypes.oneOf(IconList).isRequired,
  onClick: PropTypes.func,
  size: PropTypes.number,
  style: PropTypes.oneOfType([PropTypes.array, PropTypes.object]),
};

Icon.defaultProps = {
  color: '#1D2327',
  size: 24,
};

export default Icon;
